### ISSUE TITLE
CLI in ssh mode cannot read existing ed25519 keys

### ISSUE THREAD

**Issue by zedalaye** [archethic-foundation/archethic-cli#54]
### Describe the problem you discovered

Curious about the ssh-mode of ArchEthic CLI, I just ran :

```
$ go run . create-keychain --ssh --ssh-path ~/.ssh/id_ed25519_gitlab 
Enter passphrase for key '/home/<me>/.ssh/id_ed25519_gitlab': 
Error: Error -32602: Invalid params #/version => Expected the value to be <= 2
```

Not sure if it is expected.

**Comment by samuelmanzanera** [comment]
Hi.
Thanks for the report.
I was able to reproduce it, we will look for it.

**Comment by samuelmanzanera** [comment]
@zedalaye The issue is the current version of the CLI matches the testnet's implementation and not the mainnet one.
To make it working with the current version, add the additional flag `--endpoint https://testnet.archethic.net`

Otherwise, to continue to use the CLI on the mainnet, please downgrade version using:
`go install github.com/archethic-foundation/archethic-cli@v1.2.0`

We will adapt the README
